### ISSUE TITLE
what if service is not http ? plain sockets or websockets supported?

### ISSUE THREAD

**Issue by EMCP** [erik78se/charm-microsample#1]
Hey Erik

on line https://github.com/erik78se/charm-microsample/blob/master/metadata.yaml#L18 I see the http protocol is utilized. but what if we are using websockets or some sort of plain socket? just use `socket` in place of `http`?

**Comment by erik78se** [comment]
It should not lake difference really as the exchange of information between
charms are just two things: host + port

The name of the interface is http but cloud really be anything.

Den sön 24 maj 2020 19:06Erik <notifications@github.com> skrev:
